bai/urls.py
from django.urls import path

from bai import views

app_name='baiapp'
urlpatterns = [
    path('index/',views.index,name='index'),
    path('introduce/',views.introduce,name='introduce'),
    # path('menu/',views.menu,name='menu'),
    path('mainc/',views.mainc,name='mainc'),
    path('login/',views.login,name='login'),
    path('loginlogic/',views.loginlogic,name='loginlogic'),
    path('register/',views.register,name='register'),
    path('registerlogic/',views.registerlogic,name='registerlogic'),
    path('checkName/',views.checkName,name='checkName'),
    path('huakuai/',views.huakuai,name='huakuai'),
    path('tst/',views.tst,name='tst'),
]

baizhi/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bai/', include('bai.urls')),
]

templates/introduce.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>百智招聘</title>
<link href="{% static 'style/authority/basic_layout.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'style/authority/common_style.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
	<div id="container">
		<table class="table" cellspacing="0" cellpadding="0" width="100%" align="center"  border="0">
		    <tr>
		      <th colspan="2">系统版本</th>
		    </tr>
		    <tr>
		      <td width="100" height="30">当前版本<span class="TableRow2"></span></td>
		      <td style="text-align:left">百智招聘系统 4.1</td>
		    </tr>
		</table>
		
	</div>

</body>
</html>

templates/main.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>百智招聘</title>
	<link href="{% static 'style/authority/main_css.css' %}" rel="stylesheet" type="text/css" />
	<link href="{% static 'style/authority/zTreeStyle.css' %}" rel="stylesheet" type="text/css">
	<script type="text/javascript" src="{% static 'scripts/jquery/jquery-1.7.1.js' %}"></script>
	<script type="text/javascript" src="{% static 'scripts/zTree/jquery.ztree.core-3.2.js' %}"></script>
	<script type="text/javascript" src="{% static 'scripts/authority/commonAll.js' %}"></script>
	<script type="text/javascript">
		/* zTree插件加载目录的处理  */
		var zTree;
		
		var setting = {
				view: {
					dblClickExpand: false,
					showLine: false,
					expandSpeed: ($.browser.msie && parseInt($.browser.version)<=6)?"":"fast"
				},
				data: {
					key: {
						name: "resourceName"
					},
					simpleData: {
						enable:true,
						idKey: "resourceID",
						pIdKey: "parentID",
						rootPId: ""
					}
				},
				callback: {
	// 				beforeExpand: beforeExpand,
	// 				onExpand: onExpand,
					onClick: zTreeOnClick			
				}
		};
		 
		var curExpandNode = null;
		function beforeExpand(treeId, treeNode) {
			var pNode = curExpandNode ? curExpandNode.getParentNode():null;
			var treeNodeP = treeNode.parentTId ? treeNode.getParentNode():null;
			for(var i=0, l=!treeNodeP ? 0:treeNodeP.children.length; i<l; i++ ) {
				if (treeNode !== treeNodeP.children[i]) {
					zTree.expandNode(treeNodeP.children[i], false);
				}
			}
			while (pNode) {
				if (pNode === treeNode) {
					break;
				}
				pNode = pNode.getParentNode();
			}
			if (!pNode) {
				singlePath(treeNode);
			}
	
		}
		function singlePath(newNode) {
			if (newNode === curExpandNode) return;
			if (curExpandNode && curExpandNode.open==true) {
				if (newNode.parentTId === curExpandNode.parentTId) {
					zTree.expandNode(curExpandNode, false);
				} else {
					var newParents = [];
					while (newNode) {
						newNode = newNode.getParentNode();
						if (newNode === curExpandNode) {
							newParents = null;
							break;
						} else if (newNode) {
							newParents.push(newNode);
						}
					}
					if (newParents!=null) {
						var oldNode = curExpandNode;
						var oldParents = [];
						while (oldNode) {
							oldNode = oldNode.getParentNode();
							if (oldNode) {
								oldParents.push(oldNode);
							}
						}
						if (newParents.length>0) {
							for (var i = Math.min(newParents.length, oldParents.length)-1; i>=0; i--) {
								if (newParents[i] !== oldParents[i]) {
									zTree.expandNode(oldParents[i], false);
									break;
								}
							}
						}else {
							zTree.expandNode(oldParents[oldParents.length-1], false);
						}
					}
				}
			}
			curExpandNode = newNode;
		}
	
		function onExpand(event, treeId, treeNode) {
			curExpandNode = treeNode;
		}
		
		/** 用于捕获节点被点击的事件回调函数  **/
		function zTreeOnClick(event, treeId, treeNode) {
			var zTree = $.fn.zTree.getZTreeObj("dleft_tab1");
			zTree.expandNode(treeNode, null, null, null, true);
	// 		zTree.expandNode(treeNode);
			// 规定：如果是父类节点，不允许单击操作
			if(treeNode.isParent){
	// 			alert("父类节点无法点击哦...");
				return false;
			}
			// 如果节点路径为空或者为"#"，不允许单击操作
			if(treeNode.accessPath=="" || treeNode.accessPath=="#"){
				//alert("节点路径为空或者为'#'哦...");
				return false;
			}
		    // 跳到该节点下对应的路径, 把当前资源ID(resourceID)传到后台，写进Session
		    rightMain(treeNode.accessPath);
		    
		    if( treeNode.isParent ){
			    $('#here_area').html('当前位置：'+treeNode.getParentNode().resourceName+'&nbsp;>&nbsp;<span style="color:#1A5CC6">'+treeNode.resourceName+'</span>');
		    }else{
			    $('#here_area').html('当前位置：系统&nbsp;>&nbsp;<span style="color:#1A5CC6">'+treeNode.resourceName+'</span>');
		    }
		};
		
		/* 上方菜单 */
		function switchTab(tabpage,tabid){
		var oItem = document.getElementById(tabpage).getElementsByTagName("li"); 
		    for(var i=0; i<oItem.length; i++){
		        var x = oItem[i];    
		        x.className = "";
			}
			if('left_tab1' == tabid){
				$(document).ajaxStart(onStart).ajaxSuccess(onStop);
			
			  	loadMenu('YEWUMOKUAI', 'dleft_tab1');
			}else  if('left_tab2' == tabid){
				$(document).ajaxStart(onStart).ajaxSuccess(onStop);
		
				loadMenu('XITONGMOKUAI', 'dleft_tab1');
			}else  if('left_tab3' == tabid){
				$(document).ajaxStart(onStart).ajaxSuccess(onStop);
	
				loadMenu('QITAMOKUAI', 'dleft_tab1');
			} 
		}
		
		
		$(document).ready(function(){
			$(document).ajaxStart(onStart).ajaxSuccess(onStop);

			loadMenu('YEWUMOKUAI', "dleft_tab1");
			// 默认展开所有节点
			if( zTree ){
				// 默认展开所有节点
				zTree.expandAll(true);
			}
		});
		
		function loadMenu(resourceType, treeObj){
			
            data = [ 
			{"accessPath":"","checked":false,"delFlag":0,"parentID":1,"resourceCode":"","resourceDesc":"","resourceGrade":2,"resourceID":3,"resourceName":"北京","resourceOrder":0,"resourceType":""},
            {"accessPath":"","checked":false,"delFlag":0,"parentID":1,"resourceCode":"","resourceDesc":"","resourceGrade":2,"resourceID":4,"resourceName":"上海","resourceOrder":0,"resourceType":""},
            {"accessPath":"","checked":false,"delFlag":0,"parentID":1,"resourceCode":"","resourceDesc":"","resourceGrade":2,"resourceID":5,"resourceName":"广州","resourceOrder":0,"resourceType":""},
            {"accessPath":"","checked":false,"delFlag":0,"parentID":1,"resourceCode":"","resourceDesc":"","resourceGrade":2,"resourceID":6,"resourceName":"深圳","resourceOrder":0,"resourceType":""},

            {"accessPath":"{% url 'baiapp:mainc' %}?city=北京&job=平面设计","checked":false,"delFlag":0,"parentID":3,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":7,"resourceName":"平面设计","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=北京&job=软件工程师","checked":false,"delFlag":0,"parentID":3,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":8,"resourceName":"软件工程师","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=北京&job=Java开发工程师","checked":false,"delFlag":0,"parentID":3,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":9,"resourceName":"Java开发工程师","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=北京&job=软件测试","checked":false,"delFlag":0,"parentID":3,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":10,"resourceName":"软件测试","resourceOrder":0,"resourceType":""},
			{"accessPath":"{% url 'baiapp:mainc' %}?city=上海&job=平面设计","checked":false,"delFlag":0,"parentID":4,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":11,"resourceName":"平面设计","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=上海&job=软件工程师","checked":false,"delFlag":0,"parentID":4,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":12,"resourceName":"软件工程师","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=上海&job=Java开发工程师","checked":false,"delFlag":0,"parentID":4,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":13,"resourceName":"Java开发工程师","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=上海&job=软件测试","checked":false,"delFlag":0,"parentID":4,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":14,"resourceName":"软件测试","resourceOrder":0,"resourceType":""},
			{"accessPath":"{% url 'baiapp:mainc' %}?city=广州&job=平面设计","checked":false,"delFlag":0,"parentID":5,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":15,"resourceName":"平面设计","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=广州&job=软件工程师","checked":false,"delFlag":0,"parentID":5,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":16,"resourceName":"软件工程师","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=广州&job=Java开发工程师","checked":false,"delFlag":0,"parentID":5,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":17,"resourceName":"Java开发工程师","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=广州&job=软件测试","checked":false,"delFlag":0,"parentID":5,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":18,"resourceName":"软件测试","resourceOrder":0,"resourceType":""},
			{"accessPath":"{% url 'baiapp:mainc' %}?city=深圳&job=平面设计","checked":false,"delFlag":0,"parentID":6,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":15,"resourceName":"平面设计","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=深圳&job=软件工程师","checked":false,"delFlag":0,"parentID":6,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":16,"resourceName":"软件工程师","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=深圳&job=Java开发工程师","checked":false,"delFlag":0,"parentID":6,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":17,"resourceName":"Java开发工程师","resourceOrder":0,"resourceType":""},
            {"accessPath":"{% url 'baiapp:mainc' %}?city=深圳&job=软件测试","checked":false,"delFlag":0,"parentID":6,"resourceCode":"","resourceDesc":"","resourceGrade":3,"resourceID":18,"resourceName":"软件测试","resourceOrder":0,"resourceType":""}];

            if(data != null){
                // 将返回的数据赋给zTree
                $.fn.zTree.init($("#"+treeObj), setting, data);
//              alert(treeObj);
                zTree = $.fn.zTree.getZTreeObj(treeObj);
                if( zTree ){
                    // 默认展开所有节点
                    zTree.expandAll(true);
                }
            }
		}
		
		//ajax start function
		function onStart(){
			$("#ajaxDialog").show();
		}
		
		//ajax stop function
		function onStop(){
	// 		$("#ajaxDialog").dialog("close");
			$("#ajaxDialog").hide();
		}
	</script>
</head>
<body >
    <div id="top">
		<div id="top_logo" style="background: white;width: 2000px">
			<img alt="logo" src="{% static 'images/common/logo.jpg' %}" width="100" height="63" style="vertical-align:middle;padding-left: 60px">
		</div>
		
	
	</div>
    <!-- side menu start -->
	<div id="side">
		<div id="left_menu">
		 	<ul id="TabPage2" style="height:200px; margin-top:50px;">
				
			</ul>
			
			
			<div id="nav_show" style="position:absolute; bottom:0; padding:10px;">
				<a href="javascript:;" id="show_hide_btn">
					<img alt="显示/隐藏" title="显示/隐藏" src="{% static 'images/common/nav_hide.png' %}" width="35" height="35">
				</a>
			</div>
		 </div>
		 <div id="left_menu_cnt">
		 	<div id="nav_module">
		 		<img src="{% static 'images/common/module_1.png' %}" width="210" height="58"/>
		 	</div>
		 	<div id="nav_resource">
		 		<ul id="dleft_tab1" class="ztree"></ul>
		 	</div>
		 </div>
	</div>
	<script type="text/javascript">
		$(function(){
			$('#TabPage2 li').click(function(){
				var index = $(this).index();
				$(this).find('img').attr('src', 'images/common/'+ (index+1) +'_hover.jpg');
				$(this).css({background:'#fff'});
				$('#nav_module').find('img').attr('src', 'images/common/module_'+ (index+1) +'.png');
				$('#TabPage2 li').each(function(i, ele){
					if( i!=index ){
						$(ele).find('img').attr('src', 'images/common/'+ (i+1) +'.jpg');
						$(ele).css({background:'#044599'});
					}
				});
				// 显示侧边栏
				switchSysBar(true);
			});
			
			// 显示隐藏侧边栏
			$("#show_hide_btn").click(function() {
		        switchSysBar();
		    });
		});
		
		/**隐藏或者显示侧边栏**/
		function switchSysBar(flag){
			var side = $('#side');
	        var left_menu_cnt = $('#left_menu_cnt');
			if( flag==true ){	// flag==true
				left_menu_cnt.show(500, 'linear');
				side.css({width:'280px'});
				$('#top_nav').css({width:'77%', left:'304px'});
	        	$('#main').css({left:'280px'});
			}else{
		        if ( left_menu_cnt.is(":visible") ) {
					left_menu_cnt.hide(10, 'linear');
					side.css({width:'60px'});
		        	$('#top_nav').css({width:'100%', left:'60px', 'padding-left':'28px'});
		        	$('#main').css({left:'60px'});
		        	$("#show_hide_btn").find('img').attr('src', '{% static "images/common/nav_show.png" %}');
		        } else {
					left_menu_cnt.show(500, 'linear');
					side.css({width:'280px'});
					$('#top_nav').css({width:'77%', left:'304px', 'padding-left':'0px'});
		        	$('#main').css({left:'280px'});
		        	$("#show_hide_btn").find('img').attr('src', '{% static "images/common/nav_hide.png" %}');
		        }
			}
		}
	</script>
    <!-- side menu start -->
    <div id="top_nav">
	 	<span id="here_area">当前位置：系统&nbsp;>&nbsp;全部</span>
	</div>
    <div id="main">
      	<iframe name="right" id="rightMain" src="{% url 'baiapp:mainc' %}" frameborder="no" scrolling="auto" width="100%" height="100%" allowtransparency="true"/>
    </div>

</body>
</html>
   
 

templates/menu.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="text/javascript" src="{% static 'scripts/jquery/jquery-1.7.1.js' %}"></script>
<link href="{% static 'style/authority/basic_layout.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'style/authority/common_style.css' %}" rel="stylesheet" type="text/css">
<script type="text/javascript" src="{% static 'scripts/authority/commonAll.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/fancybox/jquery.fancybox-1.3.4.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/fancybox/jquery.fancybox-1.3.4.pack.js' %}"></script>
<script src="{% static 'scripts/echarts.min.js' %}"></script>
<script src="{% static 'scripts/china.js' %}"></script>
    <title>百智招聘</title>
<script type="text/javascript">
</script>
<style>
</style>
</head>
<body>
	<form id="submitForm" name="submitForm" action="{% url 'baiapp:mainc' %}" method="get">
		<input type="hidden" name="allIDCheck" value="" id="allIDCheck"/>
		<input type="hidden" name="fangyuanEntity.fyXqName" value="" id="fyXqName"/>
		<div id="container">
			<div class="ui_content">
				<div class="ui_text_indent">
					<div id="box_border">
						<div id="box_top">搜索</div>
						<div id="box_center">
							<select name="fangyuanEntity.fyXqCode" id="fyXq" class="ui_select01" onchange="getFyDhListByFyXqCode();">
                                <option value=""
                                >--请选择--</option>
                                <option value="1" >城市</option>
                                <option value="2" >职位</option>
                            </select>
							<input type="text" id="fyZldz" name="fangyuanEntity.fyZldz" class="ui_input_txt02" />
							<input type="button" value="查询" class="ui_input_btn01" onclick="searchall();" />
						</div>
					</div>
				</div>
			</div>
			<div class="ui_content">
				<div class="ui_tb">
					<table class="table" cellspacing="0" cellpadding="0" width="100%" align="center" border="0">
						<tr>
							<th>姓名</th>
							<th>性别</th>
							<th>年龄</th>
							<th>期望薪资</th>
							<th>学历</th>
							<th>工作经验</th>
							<th>学校</th>
							<th>专业</th>
							<th>职位</th>
							<th>城市</th>
						</tr>
                        {% for p in page.object_list %}
                            <tr>
								<td>{{ p.name }}</td>
								<td>{{ p.sex }}</td>
								<td>{{ p.age }}</td>
								<td>{{ p.salary }}</td>
								<td>{{ p.education }}</td>
								<td>{{ p.work_experience }}</td>
								<td>{{ p.school }}</td>
								<td>{{ p.specialty }}</td>
								<td>{{ p.expect_job }}</td>
								<td>{{ p.jobsite }}</td>
							</tr>
                        {% endfor %}
					</table>
				</div>
                 <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: '人才的数量对比'
            },
            tooltip: {},
            legend: {
                data:['各地人才的数量对比']
            },
            xAxis: {
                data: ["北京","上海","广州","深圳"]
            },
            yAxis: {},
            series: [{
                name: '各地人才的数量对比',
                type: 'bar',
                data: [{{ beijing }}, {{ shanghai }}, {{ guangzhou }}, {{ shenzhen }}]
            }]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>
                      <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main1" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main1'));

        // 指定图表的配置项和数据
        var option = {
            tooltip: {},
            series : [
                {
            name: '各地人才的数量对比',
            type: 'pie',
            radius: '55%',
            data:[
                {value:{{ beijing }}, name:'北京'},
                {value:{{ shanghai }}, name:'上海'},
                {value:{{ guangzhou }}, name:'广州'},
                {value:{{ shenzhen }}, name:'深圳'},
            ],

            roseType: '',
            itemStyle: {
                normal: {
                    shadowBlur: 200,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]
};

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>

    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main2" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var chart = echarts.init(document.getElementById('main2'));
        chart.setOption({
            tooltip:{},
            series: [{
                name:'用户分布图',
                type: 'map',
                map: 'china',
                data:[{name:'北京',value:{{beijing}}},{name:'上海',value:{{shanghai}}},{name:'广东',value:{{guangzhou}}},{name:'深圳',value:{{shenzhen}}},]
            }]
        });
        // 异步加载数据
        $.get('/get_map_datas').done(function (data) {
			 // data的格式{data:[{name='省名',value:值}]}
             //填入数据
            chart.setOption({
                series: [{
                    data:data.data
                }]
            });
         });
    </script>

              <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main3" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var chart = echarts.init(document.getElementById('main3'));
        var option = {
    title: {
        text: '各地人才数量对比',
        {#subtext: '纯属虚构'#}
    },
    tooltip: {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c}%"
    },
    toolbox: {
        feature: {
            dataView: {readOnly: false},
            restore: {},
            saveAsImage: {}
        }
    },
    legend: {
        data: ['北京','上海','广州','深圳']
    },
    calculable: true,
    series: [
        {
            name:'各地人才数量对比',
            type:'funnel',
            left: '10%',
            top: 60,
            //x2: 80,
            bottom: 60,
            width: '80%',
            // height: {totalHeight} - y - y2,
            min: 0,
            max: 100,
            minSize: '0%',
            maxSize: '100%',
            sort: 'descending',
            gap: 2,
            label: {
                show: true,
                position: 'inside'
            },
            labelLine: {
                length: 10,
                lineStyle: {
                    width: 1,
                    type: 'solid'
                }
            },
            itemStyle: {
                borderColor: '#fff',
                borderWidth: 1
            },
            emphasis: {
                label: {
                    fontSize: 20
                }
            },
            data: [
                {value: {{ shenzhen }}, name: '深圳'},
                {value: {{ guangzhou }}, name: '广州'},
                {value: {{ shanghai }}, name: '上海'},
                {value: {{ beijing }}, name: '北京'}
            ]
        }
    ]
};

// 使用刚指定的配置项和数据显示图表。
        chart.setOption(option);
    </script>

				<div class="ui_tb_h30">
					<div class="ui_flt" style="height: 30px; line-height: 30px;">
						共有
						<span class="ui_txt_bold04">{{ page.paginator.count }}</span>
						条记录，当前第
						<span class="ui_txt_bold04">{{ page.number }}
						/{{ page.paginator.num_pages }}</span>
						页
					</div>

					<div class="ui_frt">
						<!--    如果是第一页，则只显示下一页、尾页 -->
                            <a id="a1" style="display: none">{{ city }}</a>
                            <a id="a2" style="display: none">{{ job }}</a>
							<input type="button" value="首页" class="ui_input_btn01" onclick="firstpage()" name="first"/>
						{% if page.has_previous %}
                            <input type="button" value="上一页" class="ui_input_btn01" onclick="prev({{ page.previous_page_number }})" name="previous" />
						{% endif %}
                            {% if page.has_next %}
                                <input type="button" value="下一页" class="ui_input_btn01" name="next"
                                    onclick="nextpage({{ page.next_page_number }})" />
                            {% endif %}
							<input type="button" value="尾页" class="ui_input_btn01" name="last"
								onclick="lastpage({{ page.paginator.num_pages }});" />
							<!--     如果是最后一页，则只显示首页、上一页 -->
						
						转到第<input type="text" id="jumpNumTxt" class="ui_input_txt01" />页
							 <input type="button" class="ui_input_btn01" value="跳转" onclick="jumpInputPage();" />
					</div>

				</div>
			</div>
		</div>
	</form>
<script>


    function firstpage() {
        location.href = "{% url 'baiapp:mainc' %}?number=1"
    }
    function prev(previous) {
        location.href = "{% url 'baiapp:mainc' %}?number="+previous
    }

    function nextpage(next) {
        city=document.getElementById('a1').text
        job=document.getElementById('a2').text
        location.href = "{% url 'baiapp:mainc' %}?number="+next+"&city="+city+"&job="+job

    }
    function lastpage(last) {
        location.href = "{% url 'baiapp:mainc' %}?number="+last
    }
    function jumpInputPage() {
        jumppage=document.getElementById('jumpNumTxt').value
        location.href = "{% url 'baiapp:mainc' %}?number="+jumppage
    }
    function searchall() {
        searchtext=document.getElementById('fyZldz').value
        cj=jQuery('#fyXq option:selected').text()
        {#jobs=document.getElementById('jobs').value#}
        location.href = "{% url 'baiapp:mainc' %}?searchtext="+searchtext+"&cj="+cj
    }

</script>
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <title>ECharts</title>
    <!-- 引入 echarts.js -->
    <script src="{% static 'scripts/echarts.min.js' %}"></script>
</head>
<body>
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div id="main" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var option = {
            title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['各地人才的数量对比']
            },
            xAxis: {
                data: ["北京","上海","广州","深圳"]
            },
            yAxis: {},
            series: [{
                name: '各地人才的数量对比',
                type: 'bar',
                data: [5, 20, 36, 10]
            }]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);
    </script>
</body>
</html>